### ISSUE TITLE
Does not work for me

### ISSUE THREAD

**Issue by Djongov** [ColonelParrot/ProtectImage.js#1]
Hey,

Great idea and great library. I tested in a single html file and it worked good. So i decied to put it on my production site. For some reason it doesn't want to do anything. I tested and the file and the init() are firing.

You can check it live:

https://www.diablo-2.net/

There is an image "world-map-act-1.png" on the front page. Any idea why it's not doing the canvasing? It has the protected attr, the script is loaded (renamed to protect.min.js) and the 

window.onload = function() {
  ProtectImageJS.init()
}

is in a local file called inline.js which is also loading properly.

Any ideas?

**Comment by ColonelParrot** [comment]
Hello,

Thanks for reaching out.

I've tried running `ProtectImageJS.init()` on the browser client-side and it seems to work. I'm under the suspicion that the image has not loaded when you tried protecting the images.

I'll continue investigating. For now, try moving the `<script>` tag to the bottom of the `<body>` tag.

Best of luck,
CP
